"""rbac core

Revision ID: 0003
Revises: 0002
Created: 2026-07-30 22:33:11.784112
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0003'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_widgets',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('subtitle', sa.String(length=240), nullable=False),
    sa.Column('component', sa.String(length=64), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('size', sa.String(length=16), nullable=False),
    sa.Column('icon', sa.String(length=64), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboard_widgets_code'), 'dashboard_widgets', ['code'], unique=True)
    op.create_index(op.f('ix_dashboard_widgets_deleted_at'), 'dashboard_widgets', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_dashboard_widgets_level'), 'dashboard_widgets', ['level'], unique=False)
    op.create_table('menus',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('icon', sa.String(length=64), nullable=False),
    sa.Column('route', sa.String(length=64), nullable=True),
    sa.Column('parent_id', sa.String(length=32), nullable=True),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('module_code', sa.String(length=64), nullable=True),
    sa.Column('section', sa.String(length=64), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['menus.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menus_code'), 'menus', ['code'], unique=True)
    op.create_index(op.f('ix_menus_deleted_at'), 'menus', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_menus_level'), 'menus', ['level'], unique=False)
    op.create_index(op.f('ix_menus_module_code'), 'menus', ['module_code'], unique=False)
    op.create_index(op.f('ix_menus_parent_id'), 'menus', ['parent_id'], unique=False)
    op.create_table('modules',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('icon', sa.String(length=64), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('banner_url', sa.String(length=500), nullable=True),
    sa.Column('redirect_url', sa.String(length=500), nullable=True),
    sa.Column('login_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modules_category'), 'modules', ['category'], unique=False)
    op.create_index(op.f('ix_modules_code'), 'modules', ['code'], unique=True)
    op.create_index(op.f('ix_modules_deleted_at'), 'modules', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_modules_status'), 'modules', ['status'], unique=False)
    op.create_table('permission_groups',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permission_groups_code'), 'permission_groups', ['code'], unique=True)
    op.create_index(op.f('ix_permission_groups_deleted_at'), 'permission_groups', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_permission_groups_level'), 'permission_groups', ['level'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('resource', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('group_id', sa.String(length=32), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['permission_groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_action'), 'permissions', ['action'], unique=False)
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_index(op.f('ix_permissions_deleted_at'), 'permissions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_permissions_group_id'), 'permissions', ['group_id'], unique=False)
    op.create_index(op.f('ix_permissions_level'), 'permissions', ['level'], unique=False)
    op.create_index(op.f('ix_permissions_resource'), 'permissions', ['resource'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=True),
    sa.Column('is_template', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_readonly', sa.Boolean(), nullable=False),
    sa.Column('icon', sa.String(length=64), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'code', name='uq_roles_org_code')
    )
    op.create_index(op.f('ix_roles_code'), 'roles', ['code'], unique=False)
    op.create_index(op.f('ix_roles_deleted_at'), 'roles', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_roles_is_template'), 'roles', ['is_template'], unique=False)
    op.create_index(op.f('ix_roles_level'), 'roles', ['level'], unique=False)
    op.create_index(op.f('ix_roles_org_id'), 'roles', ['org_id'], unique=False)
    op.create_table('dashboard_permissions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('widget_id', sa.String(length=32), nullable=False),
    sa.Column('permission_id', sa.String(length=32), nullable=True),
    sa.Column('role_code', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['widget_id'], ['dashboard_widgets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('widget_id', 'permission_id', 'role_code', name='uq_dash_widget_grant')
    )
    op.create_index(op.f('ix_dashboard_permissions_permission_id'), 'dashboard_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_dashboard_permissions_role_code'), 'dashboard_permissions', ['role_code'], unique=False)
    op.create_index(op.f('ix_dashboard_permissions_widget_id'), 'dashboard_permissions', ['widget_id'], unique=False)
    op.create_table('module_permissions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('module_id', sa.String(length=32), nullable=False),
    sa.Column('permission_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module_id', 'permission_id', name='uq_module_perm')
    )
    op.create_index(op.f('ix_module_permissions_module_id'), 'module_permissions', ['module_id'], unique=False)
    op.create_index(op.f('ix_module_permissions_permission_id'), 'module_permissions', ['permission_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.String(length=32), nullable=False),
    sa.Column('permission_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('sidebar_permissions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('menu_id', sa.String(length=32), nullable=False),
    sa.Column('permission_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('menu_id', 'permission_id', name='uq_sidebar_menu_perm')
    )
    op.create_index(op.f('ix_sidebar_permissions_menu_id'), 'sidebar_permissions', ['menu_id'], unique=False)
    op.create_index(op.f('ix_sidebar_permissions_permission_id'), 'sidebar_permissions', ['permission_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('role_id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=True),
    sa.Column('assigned_by', sa.String(length=32), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_index(op.f('ix_user_roles_org_id'), 'user_roles', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_roles_org_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_sidebar_permissions_permission_id'), table_name='sidebar_permissions')
    op.drop_index(op.f('ix_sidebar_permissions_menu_id'), table_name='sidebar_permissions')
    op.drop_table('sidebar_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_module_permissions_permission_id'), table_name='module_permissions')
    op.drop_index(op.f('ix_module_permissions_module_id'), table_name='module_permissions')
    op.drop_table('module_permissions')
    op.drop_index(op.f('ix_dashboard_permissions_widget_id'), table_name='dashboard_permissions')
    op.drop_index(op.f('ix_dashboard_permissions_role_code'), table_name='dashboard_permissions')
    op.drop_index(op.f('ix_dashboard_permissions_permission_id'), table_name='dashboard_permissions')
    op.drop_table('dashboard_permissions')
    op.drop_index(op.f('ix_roles_org_id'), table_name='roles')
    op.drop_index(op.f('ix_roles_level'), table_name='roles')
    op.drop_index(op.f('ix_roles_is_template'), table_name='roles')
    op.drop_index(op.f('ix_roles_deleted_at'), table_name='roles')
    op.drop_index(op.f('ix_roles_code'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_resource'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_level'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_group_id'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_deleted_at'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_action'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_permission_groups_level'), table_name='permission_groups')
    op.drop_index(op.f('ix_permission_groups_deleted_at'), table_name='permission_groups')
    op.drop_index(op.f('ix_permission_groups_code'), table_name='permission_groups')
    op.drop_table('permission_groups')
    op.drop_index(op.f('ix_modules_status'), table_name='modules')
    op.drop_index(op.f('ix_modules_deleted_at'), table_name='modules')
    op.drop_index(op.f('ix_modules_code'), table_name='modules')
    op.drop_index(op.f('ix_modules_category'), table_name='modules')
    op.drop_table('modules')
    op.drop_index(op.f('ix_menus_parent_id'), table_name='menus')
    op.drop_index(op.f('ix_menus_module_code'), table_name='menus')
    op.drop_index(op.f('ix_menus_level'), table_name='menus')
    op.drop_index(op.f('ix_menus_deleted_at'), table_name='menus')
    op.drop_index(op.f('ix_menus_code'), table_name='menus')
    op.drop_table('menus')
    op.drop_index(op.f('ix_dashboard_widgets_level'), table_name='dashboard_widgets')
    op.drop_index(op.f('ix_dashboard_widgets_deleted_at'), table_name='dashboard_widgets')
    op.drop_index(op.f('ix_dashboard_widgets_code'), table_name='dashboard_widgets')
    op.drop_table('dashboard_widgets')
    # ### end Alembic commands ###
