"""commerce catalog pricing payments

Revision ID: 0004
Revises: 0003
Created: 2026-07-30 23:07:46.541810
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0004'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enquiries',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('company', sa.String(length=160), nullable=False),
    sa.Column('contact_name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=False),
    sa.Column('country', sa.String(length=80), nullable=False),
    sa.Column('module_codes', sa.JSON(), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('assigned_to', sa.String(length=200), nullable=True),
    sa.Column('internal_note', sa.Text(), nullable=False),
    sa.Column('notified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enquiries_deleted_at'), 'enquiries', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_enquiries_email'), 'enquiries', ['email'], unique=False)
    op.create_index(op.f('ix_enquiries_status'), 'enquiries', ['status'], unique=False)
    op.create_table('payment_gateways',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_test_mode', sa.Boolean(), nullable=False),
    sa.Column('currencies', sa.JSON(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_gateways_code'), 'payment_gateways', ['code'], unique=True)
    op.create_index(op.f('ix_payment_gateways_deleted_at'), 'payment_gateways', ['deleted_at'], unique=False)
    op.create_table('plans',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('module_id', sa.String(length=32), nullable=True),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('excluded', sa.JSON(), nullable=False),
    sa.Column('limits', sa.JSON(), nullable=False),
    sa.Column('billing_cycle', sa.String(length=24), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('scope', sa.String(length=160), nullable=False),
    sa.Column('action', sa.String(length=24), nullable=False),
    sa.Column('min_qty', sa.Integer(), nullable=False),
    sa.Column('is_popular', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module_id', 'code', name='uq_plan_module_code')
    )
    op.create_index(op.f('ix_plans_code'), 'plans', ['code'], unique=False)
    op.create_index(op.f('ix_plans_deleted_at'), 'plans', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_plans_module_id'), 'plans', ['module_id'], unique=False)
    op.create_table('plan_prices',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('plan_id', sa.String(length=32), nullable=False),
    sa.Column('country_code', sa.String(length=4), nullable=False),
    sa.Column('currency', sa.String(length=4), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('period', sa.String(length=32), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'country_code', name='uq_price_plan_country')
    )
    op.create_index(op.f('ix_plan_prices_country_code'), 'plan_prices', ['country_code'], unique=False)
    op.create_index(op.f('ix_plan_prices_deleted_at'), 'plan_prices', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_plan_prices_plan_id'), 'plan_prices', ['plan_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('module_code', sa.String(length=64), nullable=False),
    sa.Column('plan_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_deleted_at'), 'subscriptions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_subscriptions_expires_at'), 'subscriptions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_subscriptions_module_code'), 'subscriptions', ['module_code'], unique=False)
    op.create_index(op.f('ix_subscriptions_org_id'), 'subscriptions', ['org_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=True),
    sa.Column('plan_id', sa.String(length=32), nullable=True),
    sa.Column('module_code', sa.String(length=64), nullable=True),
    sa.Column('gateway_code', sa.String(length=32), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=4), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('description', sa.String(length=240), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_deleted_at'), 'transactions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_transactions_gateway_code'), 'transactions', ['gateway_code'], unique=False)
    op.create_index(op.f('ix_transactions_module_code'), 'transactions', ['module_code'], unique=False)
    op.create_index(op.f('ix_transactions_org_id'), 'transactions', ['org_id'], unique=False)
    op.create_index(op.f('ix_transactions_reference'), 'transactions', ['reference'], unique=False)
    op.create_index(op.f('ix_transactions_status'), 'transactions', ['status'], unique=False)
    op.add_column('modules', sa.Column('tagline', sa.String(length=240), nullable=False))
    op.add_column('modules', sa.Column('features', sa.JSON(), nullable=False))
    op.add_column('modules', sa.Column('is_public', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modules', 'is_public')
    op.drop_column('modules', 'features')
    op.drop_column('modules', 'tagline')
    op.drop_index(op.f('ix_transactions_status'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_reference'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_org_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_module_code'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_gateway_code'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_deleted_at'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_org_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_module_code'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_expires_at'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_deleted_at'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_plan_prices_plan_id'), table_name='plan_prices')
    op.drop_index(op.f('ix_plan_prices_deleted_at'), table_name='plan_prices')
    op.drop_index(op.f('ix_plan_prices_country_code'), table_name='plan_prices')
    op.drop_table('plan_prices')
    op.drop_index(op.f('ix_plans_module_id'), table_name='plans')
    op.drop_index(op.f('ix_plans_deleted_at'), table_name='plans')
    op.drop_index(op.f('ix_plans_code'), table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_payment_gateways_deleted_at'), table_name='payment_gateways')
    op.drop_index(op.f('ix_payment_gateways_code'), table_name='payment_gateways')
    op.drop_table('payment_gateways')
    op.drop_index(op.f('ix_enquiries_status'), table_name='enquiries')
    op.drop_index(op.f('ix_enquiries_email'), table_name='enquiries')
    op.drop_index(op.f('ix_enquiries_deleted_at'), table_name='enquiries')
    op.drop_table('enquiries')
    # ### end Alembic commands ###
