"""media uploads and app settings

Revision ID: 0006
Revises: 0005
Created: 2026-07-31 18:22:43.950314
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0006'
down_revision: Union[str, None] = '0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('namespace', sa.String(length=64), nullable=False),
    sa.Column('values', sa.JSON(), nullable=False),
    sa.Column('secrets', sa.JSON(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_settings_deleted_at'), 'app_settings', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_app_settings_namespace'), 'app_settings', ['namespace'], unique=True)
    op.add_column('modules', sa.Column('thumbnail_url', sa.String(length=500), nullable=True))
    op.add_column('modules', sa.Column('preview_video_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modules', 'preview_video_url')
    op.drop_column('modules', 'thumbnail_url')
    op.drop_index(op.f('ix_app_settings_namespace'), table_name='app_settings')
    op.drop_index(op.f('ix_app_settings_deleted_at'), table_name='app_settings')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
