#!/usr/bin/env python
"""
manage.py — database CLI for the GoalCert Hub backend.

Run from anywhere; it always resolves the migrations next to this file.

    python manage.py migrate                  # apply everything (upgrade head)
    python manage.py makemigrations -m "add teams table"
    python manage.py current                  # where is this database?
    python manage.py history                  # what exists?
    python manage.py downgrade                # undo the last migration
    python manage.py seed                     # super admin + demo orgs

It is a thin wrapper over Alembic — `alembic upgrade head` and friends work
just as well from hub/backend. The wrapper exists so the commands are the same
on every machine (no PATH games with the venv's alembic.exe) and so `seed`
lives next to them.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

BACKEND_DIR = Path(__file__).resolve().parent
if str(BACKEND_DIR) not in sys.path:
    sys.path.insert(0, str(BACKEND_DIR))

# Windows consoles default to cp1252 and blow up on any non-ASCII character in
# a migration's docstring. Migrations must never fail over a dash.
for _stream in (sys.stdout, sys.stderr):
    try:
        _stream.reconfigure(encoding="utf-8", errors="replace")
    except (AttributeError, ValueError):  # not a reconfigurable stream
        pass

ALEMBIC_INI = BACKEND_DIR / "alembic.ini"
MIGRATIONS_DIR = BACKEND_DIR / "migrations"


def _config():
    """Alembic config with absolute paths, so cwd never matters."""
    from alembic.config import Config

    cfg = Config(str(ALEMBIC_INI))
    cfg.set_main_option("script_location", str(MIGRATIONS_DIR))
    return cfg


def _safe_url() -> str:
    """DATABASE_URL with any password redacted — safe to print in logs."""
    from db import DATABASE_URL

    try:
        from sqlalchemy.engine import make_url

        return make_url(DATABASE_URL).render_as_string(hide_password=True)
    except Exception:
        return DATABASE_URL


# ── commands ──────────────────────────────────────────────────────────


def cmd_upgrade(args) -> None:
    from alembic import command

    print(f"-> upgrading {_safe_url()} to {args.revision}")
    command.upgrade(_config(), args.revision, sql=args.sql)
    if not args.sql:
        print("OK: database is at head")


def cmd_downgrade(args) -> None:
    from alembic import command

    print(f"-> downgrading {_safe_url()} to {args.revision}")
    command.downgrade(_config(), args.revision, sql=args.sql)


def _next_rev_id() -> str:
    """0001, 0002, 0003... — Alembic's random hashes don't sort; these do."""
    used = []
    for f in MIGRATIONS_DIR.joinpath("versions").glob("[0-9][0-9][0-9][0-9]_*.py"):
        used.append(int(f.name[:4]))
    return f"{(max(used) + 1) if used else 1:04d}"


def cmd_makemigrations(args) -> None:
    """New revision. Autogenerated from the models unless --empty is passed."""
    from alembic import command

    command.revision(
        _config(),
        message=args.message,
        autogenerate=not args.empty,
        rev_id=args.rev_id or _next_rev_id(),
    )
    print("OK: review the generated file before committing it")


def cmd_current(args) -> None:
    from alembic import command

    print(f"database: {_safe_url()}")
    command.current(_config(), verbose=args.verbose)


def cmd_history(args) -> None:
    from alembic import command

    command.history(_config(), verbose=args.verbose, indicate_current=True)


def cmd_heads(args) -> None:
    from alembic import command

    command.heads(_config(), verbose=args.verbose)


def cmd_stamp(args) -> None:
    """Record a revision as applied WITHOUT running it (adopting an existing DB)."""
    from alembic import command

    command.stamp(_config(), args.revision)
    print(f"OK: stamped {args.revision} (no SQL was run)")


def cmd_seed(args) -> None:
    from seed import seed_super_admin
    from seed_clients import seed_demo_orgs

    seed_super_admin()
    seed_demo_orgs()
    print("OK: seeded super admin + demo organisations")


# ── entry point ───────────────────────────────────────────────────────


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="python manage.py",
        description="GoalCert Hub — database migrations",
    )
    sub = p.add_subparsers(dest="command", required=True)

    for name, help_text in (("upgrade", "apply migrations"), ("migrate", "alias for upgrade")):
        up = sub.add_parser(name, help=help_text)
        up.add_argument("revision", nargs="?", default="head",
                        help="target revision (default: head)")
        up.add_argument("--sql", action="store_true",
                        help="print the SQL instead of running it")
        up.set_defaults(func=cmd_upgrade)

    down = sub.add_parser("downgrade", help="revert migrations")
    down.add_argument("revision", nargs="?", default="-1",
                      help="target revision (default: -1, one step back)")
    down.add_argument("--sql", action="store_true", help="print the SQL instead of running it")
    down.set_defaults(func=cmd_downgrade)

    for name in ("makemigrations", "revision"):
        mk = sub.add_parser(name, help="create a new migration from the models")
        mk.add_argument("-m", "--message", required=True, help="short description")
        mk.add_argument("--empty", action="store_true",
                        help="hand-written migration (skip autogenerate)")
        mk.add_argument("--rev-id", dest="rev_id", default=None,
                        help="revision id (default: the next number, e.g. 0002)")
        mk.set_defaults(func=cmd_makemigrations)

    cur = sub.add_parser("current", help="show the revision this database is on")
    cur.add_argument("-v", "--verbose", action="store_true")
    cur.set_defaults(func=cmd_current)

    hist = sub.add_parser("history", help="list all migrations")
    hist.add_argument("-v", "--verbose", action="store_true")
    hist.set_defaults(func=cmd_history)

    heads = sub.add_parser("heads", help="show the latest revision(s) on disk")
    heads.add_argument("-v", "--verbose", action="store_true")
    heads.set_defaults(func=cmd_heads)

    stamp = sub.add_parser("stamp", help="mark a revision applied without running it")
    stamp.add_argument("revision", nargs="?", default="head")
    stamp.set_defaults(func=cmd_stamp)

    seed = sub.add_parser("seed", help="seed the super admin + demo organisations")
    seed.set_defaults(func=cmd_seed)

    return p


def main() -> int:
    args = build_parser().parse_args()
    try:
        args.func(args)
    except Exception as exc:  # noqa: BLE001 — CLI: a traceback helps nobody here
        print(f"ERROR: {type(exc).__name__}: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
